exports.tables = {
    Students: 'students',
    OtpCodes: 'otp_codes',
    Hobbies: 'hobbies',
    Interests: 'interests',
    Campuses: 'campuses',
    Programs: 'programs',
    StudentStatuses: 'student_statuses',
    ActivityStatuses: 'activity_statuses',
    ActivityTypes: 'activity_types',
    CampusSpots: 'campus_spots',
    Activities: 'activities',
    ActivityAttendees: 'activity_attendees',
    SavedActivities: 'saved_activities',
    StudentConnections: 'student_connections',
    HangoutRequests: 'hangout_requests',
    ReactionTypes: 'reaction_types',
    Posts: 'posts',
    PostResources: 'post_resources',
    PostReactions: 'post_reactions',
    Subjects: 'subjects',
    Timeslots: 'timeslots'
};